all:
  hosts:
    web-1:
        ansible_host: 89.169.137.1
        ansible_user: ubuntu
    web-2:
        ansible_host: 89.169.134.97
        ansible_user: ubuntu
    main:
        ansible_host: 
        ansible_user: ubuntu
    replica:
        ansible_host: 
        ansible_user: ubuntu
    storage:
        ansible_host: 89.169.138.56
        ansible_user: ubuntu
  