all:
  hosts:
    web-1:
        ansible_host: 51.250.68.188
        ansible_user: ubuntu
    web-2:
        ansible_host: 51.250.95.242
        ansible_user: ubuntu
    main:
        ansible_host: 
        ansible_user: ubuntu
    replica:
        ansible_host: 
        ansible_user: ubuntu
    storage:
        ansible_host: 89.169.156.29
        ansible_user: ubuntu
  