all:
  hosts:
    web-1:
        ansible_host: 89.169.136.216
        ansible_user: ubuntu
    web-2:
        ansible_host: 51.250.8.12
        ansible_user: ubuntu
    main:
        ansible_host: 
        ansible_user: ubuntu
    replica:
        ansible_host: 
        ansible_user: ubuntu
    storage:
        ansible_host: 89.169.157.151
        ansible_user: ubuntu
  