all:
  hosts:
    web-1:
        ansible_host: 89.169.155.124
        ansible_user: ubuntu
    web-2:
        ansible_host: 89.169.159.246
        ansible_user: ubuntu
    main:
        ansible_host: 
        ansible_user: ubuntu
    replica:
        ansible_host: 
        ansible_user: ubuntu
    storage:
        ansible_host: 89.169.147.129
        ansible_user: ubuntu
  